development:
  clients:
    default:
      database: 33_minutes_server_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: 33_minutes_server_test
      hosts:
        - localhost:27017
      read:
        mode: :primary
      max_pool_size: 1


production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      raise_not_found_error: false
      use_utc: true
